Add failure step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -104,6 +104,15 @@ jobs:
         run: |
           cat env.list >> $GITHUB_ENV
 
+      - name: Test fail
+        run: |
+          set -o verbose
+          echo "line 1"
+          echo "line 2"; false
+          echo "line 3"
+          echo "line 4"; false
+          echo "line 5"
+
       #- name: Check terminfo
       #  run: find /usr/share/terminfo -type f | sort
 
@@ -274,11 +283,6 @@ jobs:
       #    CC=gcc pip3 install --user cpp-coveralls pyopenssl ndg-httpsclient pyasn1
       #    ls ~/.local/bin
 
-      - name: Test fail
-        if: startsWith(matrix.os, 'ubuntu-')
-        run: |
-          false
-
       - name: Run Ubuntu
         run: |
           echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
@@ -293,42 +297,42 @@ jobs:
           pgrep -fl Xvfb || true
           sudo systemctl status xvfb.service
 
-  postproc:
-    runs-on: ubuntu-latest
-
-    needs: trial-on-linux
-    if: needs.trial-on-linux.result != 'skipped'
-
-    steps:
-      - name: done
-        run: |
-          echo "END"
-
-  trial-on-macos:
-    runs-on: ${{ matrix.os }}
-
-    env:
-      CC: ${{ matrix.compiler }}
-
-    strategy:
-      fail-fast: true
-      matrix:
-        os: [macos-10.14, macos-10.15, macos-11.0]
-        compiler: [gcc, clang]
-
-    steps:
-      - name: Show environment
-        run: |
-          uname -a
-          sw_vers
-
-      - name: Run macOS
-        if: matrix.os == 'macos-10.15'
-        run: |
-          sudo xcode-select -s /Applications/Xcode_12.2.app
-          xcodebuild -showsdks || true
-          # xcrun --show-sdk-platform-path || true
-          # xcrun --show-sdk-platform-version || true
-          xcrun --sdk macosx11.0 cc -arch x86_64 -arch arm64e -o test.out main.c
-          file test.out
-          otool -L test.out
+  # postproc:
+  #   runs-on: ubuntu-latest
+  # 
+  #   needs: trial-on-linux
+  #   if: needs.trial-on-linux.result != 'skipped'
+  # 
+  #   steps:
+  #     - name: done
+  #       run: |
+  #         echo "END"
+  # 
+  # trial-on-macos:
+  #   runs-on: ${{ matrix.os }}
+  # 
+  #   env:
+  #     CC: ${{ matrix.compiler }}
+  # 
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       os: [macos-10.14, macos-10.15, macos-11.0]
+  #       compiler: [gcc, clang]
+  # 
+  #   steps:
+  #     - name: Show environment
+  #       run: |
+  #         uname -a
+  #         sw_vers
+  # 
+  #     - name: Run macOS
+  #       if: matrix.os == 'macos-10.15'
+  #       run: |
+  #         sudo xcode-select -s /Applications/Xcode_12.2.app
+  #         xcodebuild -showsdks || true
+  #         # xcrun --show-sdk-platform-path || true
+  #         # xcrun --show-sdk-platform-version || true
+  #         xcrun --sdk macosx11.0 cc -arch x86_64 -arch arm64e -o test.out main.c
+  #         file test.out
+  #         otool -L test.out
